version: 2

sources:
  - name: google
    schema: "{{ env_var('LANDING_DATASET_ID', 'landing_dev') }}"
    tables:
      - name: google_search

models:
  - name: google_search
    description: Clean google search results
    columns:
      - name: google_search_result_sk
        tests:
          - unique
          - not_null


tags: "google"
