version: 2

sources:
  - name: google
    schema: "{{ env_var('LANDING_DATASET_ID', 'landing_dev') }}"
    tables:
      - name: google_search

models:
  - name: google_search
    description: Clean google search results
    columns:
      - name: google_search_result_sk
        tests:
          - unique
          - not_null
  - name: google_search_artist_details
    description: Artist information from google search 
    columns:
      - name: google_search_artist_id
        tests:
          - unique
          - not_null
  - name: google_search_artist
    description: Artists extracted from google search  
    columns:
      - name: google_search_artist_id
        tests:
          - unique
          - not_null
  - name: google_search_artist_music_platform
    description: Music platform links for google artists 
    columns:
      - name: music_platform_url 
        tests:
          - unique
          - not_null
  - name: google_search_artist_social_media
    description: Music platform links for google artists 
    columns:
      - name: social_media_url 
        tests:
          - unique
          - not_null


tags: "google"
