version: 2

models:
  - name: stg_venue_spine
    description: A table containing system venue ids and how they link to other venue source tables
    columns:
      - name: venue_id
        tests:
          - unique
          - not_null
      - name: thebrag_venue_id
        tests:
          - relationships:
              to: ref('thebrag_venue')
              field: thebrag_venue_id
  - name: stg_artist_spine
    description: A table containing system artist ids and how they link to other venue source tables
    columns:
      - name: artist_id
        tests:
          - unique
          - not_null
      - name: bandcamp_artist_id
        tests:
          - relationships:
              to: ref('bandcamp_artist')
              field: bandcamp_artist_id
      - name: thebrag_artist_id
        tests:
          - relationships:
              to: ref('thebrag_artist')
              field: thebrag_artist_id
  - name: dim_venue
    description: Describes every live music venue in the system
    columns:
      - name: venue_id
        tests:
          - unique
          - not_null
    tests:
      - unique_location:
          lat: lat
          lon: lon
          distance_threshold: 5
          severity: warn

tags: "api"
