version: 2

models:
  - name: stg_venue_spine
    description: A table containing system venue ids and how they link to other venue source tables
    columns:
      - name: venue_id
        tests:
          - unique
          - not_null
      - name: thebrag_venue_id
        tests:
          - relationships:
              to: ref('thebrag_venue')
              field: thebrag_venue_id
  - name: stg_artist_spine
    description: A table containing system artist ids and how they link to other venue source tables
    columns:
      - name: artist_id
        tests:
          - unique
          - not_null
      - name: bandcamp_artist_id
        tests:
          - relationships:
              to: ref('bandcamp_artist')
              field: bandcamp_artist_id
              severity: warn
      - name: thebrag_artist_id
        tests:
          - relationships:
              to: ref('thebrag_artist')
              field: thebrag_artist_id
              severity: warn
  - name: stg_gig_spine
    description: A table containing system gig ids and how they link to other venue source tables
    columns:
      - name: gig_id
        tests:
          - unique
          - not_null
      - name: thebrag_gig_id
        tests:
          - relationships:
              to: ref('thebrag_gig_final')
              field: thebrag_gig_id
  - name: dim_gig
    description: A table containing system gigs
    columns:
      - name: gig_id
        tests:
          - unique
          - not_null
      - name: venue_id
        tests:
          - relationships:
              to: ref('dim_venue')
              field: venue_id
  - name: dim_venue
    description: Describes every live music venue in the system
    columns:
      - name: venue_id
        tests:
          - unique
          - not_null
    tests:
      - unique_location:
          lat: lat
          lon: lon
          distance_threshold: 5
          severity: warn
  - name: dim_artist
    description: A table containing all artists in the system
    columns:
      - name: artist_id
        tests:
          - unique
          - not_null
  - name: dim_artist_music
    description: A table containing links to artist music
    columns:
      - name: artist_music_id
        tests:
          - unique
          - not_null
      - name: artist_id
        tests:
          - relationships:
              to: ref('dim_artist')
              field: artist_id
  - name: dim_artist_social
    description: A table containing social media links related to an artist
    columns:
      - name: artist_social_url
        tests:
          - unique
          - not_null
      - name: artist_id
        tests:
          - relationships:
              to: ref('dim_artist')
              field: artist_id

tags: "api"
