version: 2

models:
  - name: stg_venue_spine
    description: A table containing system venue ids and how they link to other venue source tables
    columns:
      - name: venue_id
        tests:
          - unique
          - not_null
  - name: venue
    description: Describes every live music venue in the system
    columns:
      - name: venue_id
        tests:
          - unique
          - not_null

tags: "api"
