melbourne_gig_guide_dbt:
  outputs:
    dw:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET_ID') }}"
      threads: 16
      timeout_seconds: 300
      priority: interactive
      retries: 1
  target: dw
